apiVersion: v1
kind: Service
metadata:
  name: semantic-search-service
  namespace: xirify-dev-ns
spec:
  selector:
    app: semantic-search
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP
